// Cafe Gather × AIRPORTELS — drink menu.
// Extracted from the cafe's real public menu (bakery + coffee-bean products excluded).
// Each drink carries a CSS/SVG-render recipe so we don't ship any image files.
//
// recipe = { type: "iced" | "hot" | "bottle" | "can",
//            base:  CSS color (main liquid),
//            top:   CSS color | null (upper layer — foam / pour / fruit pulp),
//            topPct: 0..1   (how tall the top band is, default 0.28),
//            label: string  (one or two ALL-CAPS lines printed on the cup/can),
//            labelBg: CSS color (bottle/can label paper background),
//            inkOnLabel: CSS color (text color on the label) }

window.MENU_CATEGORIES = [
  { id: "espresso", label: "Espresso" },
  { id: "matcha",   label: "Matcha" },
  { id: "tea",      label: "Tea & Milk" },
  { id: "cocoa",    label: "Cocoa" },
  { id: "soda",     label: "Craft Soda" },
  { id: "juice",    label: "Juice & More" },
  { id: "summer",   label: "Summer" },
  { id: "hot",      label: "Hot Menu" }
];

window.MENU = [
  // ───────── ESPRESSO ─────────
  { id: "iced-americano", cat: "espresso", name: "Iced Americano", thai: "อเมริกาโน่",
    desc: "Bright espresso lengthened with cold water. The bestseller.",
    price: 89, temps: ["iced"], opts: ["sugar", "roast"], bestseller: 1,
    recipe: { type: "iced", base: "#2a1810", top: null, label: "AMERICANO" } },
  { id: "iced-cappuccino", cat: "espresso", name: "Iced Cappuccino", thai: "คาปูชิโน่",
    desc: "Cold milk + dense espresso foam.",
    price: 99, temps: ["iced"], opts: ["sugar", "roast"],
    recipe: { type: "iced", base: "#7a5536", top: "#e8d4b8", topPct: 0.22, label: "CAPPUCCINO" } },
  { id: "black-orange", cat: "espresso", name: "Black Orange", thai: "กาแฟส้ม",
    desc: "Americano poured over fresh orange. Tangy, sweet, bitter all at once.",
    price: 109, temps: ["iced"], opts: ["sugar", "roast"], bestseller: 4,
    recipe: { type: "iced", base: "#e89216", top: "#2a1810", topPct: 0.42, label: "BLACK\nORANGE" } },
  { id: "iced-cafe-latte", cat: "espresso", name: "Ice Cafe Latte", thai: "ลาเต้",
    desc: "Cold milk, double espresso, smooth & balanced.",
    price: 99, temps: ["iced"], opts: ["sugar", "roast"], bestseller: 2,
    recipe: { type: "iced", base: "#7e5234", top: "#e8d4b8", topPct: 0.24, label: "CAFE LATTE" } },
  { id: "es-yen", cat: "espresso", name: "Es-Yen", thai: "กาแฟเย็น",
    desc: "Thai-style sweet condensed-milk coffee. Classic.",
    price: 99, temps: ["iced"], opts: ["sugar", "roast"], bestseller: 5,
    recipe: { type: "iced", base: "#a07a52", top: "#d8b88a", topPct: 0.18, label: "ES-YEN" } },
  { id: "iced-mocha", cat: "espresso", name: "Iced Mocha", thai: "ม็อคค่า",
    desc: "Espresso + real chocolate + cold milk. Dessert in a cup.",
    price: 99, temps: ["iced"], opts: ["sugar", "roast"],
    recipe: { type: "iced", base: "#3a2418", top: "#d8c0a4", topPct: 0.28, label: "MOCHA" } },
  { id: "iced-breve", cat: "espresso", name: "Iced Breve", thai: "เบรฟ (วิปครีม)",
    desc: "Espresso shaken with cream. Dense, silky, rich.",
    price: 99, temps: ["iced"], opts: ["sugar", "roast"],
    recipe: { type: "iced", base: "#a47854", top: "#f1e2c9", topPct: 0.30, label: "BREVE" } },
  { id: "iced-caramel-macchiato", cat: "espresso", name: "Iced Caramel Macchiato", thai: "คาราเมล มัคคิอาโต้",
    desc: "Cold milk, caramel ribbon, espresso on top.",
    price: 99, temps: ["iced"], opts: ["sugar", "roast"],
    recipe: { type: "iced", base: "#e0c08c", top: "#5a3818", topPct: 0.30, label: "CARAMEL\nMACCHIATO" } },
  { id: "iced-americano-coconut", cat: "espresso", name: "Iced Americano Coconut", thai: "กาแฟมะพร้าว",
    desc: "Americano over fresh coconut water. Tropical and dark.",
    price: 109, temps: ["iced"], opts: ["sugar", "roast"], bestseller: 6,
    recipe: { type: "iced", base: "#f0ebe2", top: "#2a1810", topPct: 0.42, label: "BLACK\nCOCONUT" } },
  { id: "toddy-palm-americano", cat: "espresso", name: "Toddy Palm Americano", thai: "อเมริกาโน่ลูกตาล",
    desc: "Americano sweetened with palm-sugar syrup.",
    price: 110, temps: ["iced"], opts: ["sugar", "roast"],
    recipe: { type: "iced", base: "#3a2418", top: "#e6c896", topPct: 0.22, label: "TODDY PALM" } },

  // ───────── MATCHA ─────────
  { id: "classic-matcha-latte", cat: "matcha", name: "Classic Matcha Latte", thai: "มัทฉะลาเต้",
    desc: "Singapark farm matcha + cold milk.",
    price: 100, temps: ["iced"], opts: ["sugar"], bestseller: 3,
    recipe: { type: "iced", base: "#f0ebd8", top: "#5a8038", topPct: 0.38, label: "MATCHA LATTE" } },
  { id: "classic-matcha-orange", cat: "matcha", name: "Classic Matcha Orange", thai: "มัทฉะส้ม",
    desc: "Matcha over fresh orange. Bittersweet, brilliant.",
    price: 120, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#e89216", top: "#5a8038", topPct: 0.36, label: "MATCHA\nORANGE" } },
  { id: "classic-matcha-coconut", cat: "matcha", name: "Classic Matcha Coconut", thai: "มัทฉะมะพร้าว",
    desc: "Matcha + coconut water. Earthy meets tropical.",
    price: 120, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#f0ebe2", top: "#5a8038", topPct: 0.36, label: "MATCHA\nCOCONUT" } },
  { id: "premium-matcha-latte", cat: "matcha", name: "Premium Matcha Latte", thai: "พรีเมี่ยมมัทฉะลาเต้",
    desc: "Organic ceremonial-grade matcha from Japan.",
    price: 130, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#f0ebd8", top: "#3e6224", topPct: 0.40, label: "MATCHA LATTE" } },
  { id: "premium-matcha-orange", cat: "matcha", name: "Premium Matcha Orange", thai: "พรีเมี่ยมมัทฉะส้ม",
    desc: "Premium organic matcha + fresh orange.",
    price: 150, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#e89216", top: "#3e6224", topPct: 0.36, label: "MATCHA\nORANGE" } },
  { id: "premium-matcha-coconut", cat: "matcha", name: "Premium Matcha Coconut", thai: "พรีเมี่ยมมัทฉะมะพร้าว",
    desc: "Premium organic matcha + coconut water.",
    price: 150, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#f0ebe2", top: "#3e6224", topPct: 0.36, label: "MATCHA\nCOCONUT" } },
  { id: "pure-classic-matcha", cat: "matcha", name: "Pure Classic Matcha", thai: "เพียวมัทฉะ",
    desc: "Just matcha + water. No milk.",
    price: 85, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#5a8038", top: null, label: "PURE MATCHA" } },
  { id: "pure-premium-matcha", cat: "matcha", name: "Pure Premium Matcha", thai: "เพียวพรีเมี่ยมมัทฉะ",
    desc: "Premium organic matcha + cold water.",
    price: 125, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#3e6224", top: null, label: "PURE MATCHA" } },

  // ───────── TEA & MILK ─────────
  // Tropical SuperFruit Tea moved here from "summer" — was the team's #1 order last week.
  { id: "tropical-superfruit-tea", cat: "tea", name: "Tropical SuperFruit Tea", thai: "ชาผลไม้", aliases: ["ชาไม้ผล"],
    desc: "Fruit tea with seasonal fresh fruit. Gather Summer special.",
    price: 165, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#e89b4c", top: null, label: "TROPICAL\nSUPERFRUIT", garnish: "fruit" } },
  { id: "iced-thai-tea", cat: "tea", name: "Iced Thai Tea", thai: "ชาไทยเย็น",
    desc: "Classic orange Thai tea + condensed milk.",
    price: 89, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#d56831", top: "#e8d4b8", topPct: 0.18, label: "THAI TEA" } },
  { id: "iced-green-tea", cat: "tea", name: "Iced Green Tea", thai: "ชาเขียวเย็น",
    desc: "Jasmine green tea + milk. Floral, light.",
    price: 89, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#7a9846", top: "#e8d4b8", topPct: 0.18, label: "GREEN TEA" } },
  { id: "iced-peach-tea", cat: "tea", name: "Iced Peach Tea", thai: "ชาพีชเย็น", aliases: ["ชาพีท", "ชานมพีช"],
    desc: "Iced peach tea. Sweet, soft.",
    price: 89, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#dc9c70", top: null, label: "PEACH TEA" } },
  { id: "iced-pure-thai-tea", cat: "tea", name: "Iced Pure Thai Tea", thai: "ชาไทยไม่ใส่สี",
    desc: "Real Thai tea — no dye. Honest amber.",
    price: 89, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#a87648", top: "#e8d4b8", topPct: 0.20, label: "PURE\nTHAI TEA" } },
  { id: "iced-caramel-milk", cat: "tea", name: "Iced Caramel Milk", thai: "นมคาราเมล",
    desc: "Cold milk + caramel ribbon. No coffee.",
    price: 79, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#f0e2c0", top: "#a87234", topPct: 0.18, label: "CARAMEL MILK" } },
  { id: "iced-fresh-milk", cat: "tea", name: "Iced Fresh Milk", thai: "นมสดเย็น",
    desc: "Just cold fresh milk. Honest.",
    price: 65, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#f6f2e8", top: null, label: "FRESH MILK" } },

  // ───────── COCOA ─────────
  { id: "iced-cocoa-latte", cat: "cocoa", name: "Iced Cocoa Latte", thai: "โกโก้เย็น", aliases: ["ช็อกโกแลต"],
    desc: "Cocoa + cold milk. Comfort drink.",
    price: 89, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#5a3220", top: "#e8d4b8", topPct: 0.22, label: "COCOA LATTE" } },
  { id: "iced-cocoa-caramel", cat: "cocoa", name: "Iced Cocoa Caramel Latte", thai: "โกโก้คาราเมล",
    desc: "Cocoa + caramel ribbon. Dessert energy.",
    price: 109, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#3a1f14", top: "#c89254", topPct: 0.26, label: "COCOA\nCARAMEL" } },
  { id: "lopburi-cocoa-latte", cat: "cocoa", name: "Lopburi Cocoa Latte", thai: "ลพบุรีโกโก้ลาเต้",
    desc: "Thai single-origin cacao from Lopburi.",
    price: 129, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#2e1610", top: "#d8b88a", topPct: 0.22, label: "LOPBURI\nCOCAO LATTE" } },
  { id: "chiang-rai-cocoa-latte", cat: "cocoa", name: "Chiang Rai Cocoa Latte", thai: "เชียงราย โกโก้ลาเต้",
    desc: "Thai single-origin cacao from Chiang Rai.",
    price: 129, temps: ["iced"], opts: ["sugar"],
    recipe: { type: "iced", base: "#2a1408", top: "#d8b88a", topPct: 0.22, label: "CHIANG RAI\nCOCOA LATTE" } },

  // ───────── CRAFT SODA ─────────
  { id: "black-tea-honey-lemon", cat: "soda", name: "Black Tea Honey Lemon", thai: "ชาดำ น้ำผึ้ง คราฟต์โซดา",
    desc: "Black tea, honey, lemon, soda.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "bottle", base: "#b88a44", label: "BLACK TEA\nHONEY LEMON", labelBg: "#fef9c3", inkOnLabel: "#5a3a08" } },
  { id: "cola-buri", cat: "soda", name: "Cola Buri (Thai Style)", thai: "ไทยโคล่า คราฟต์โซดา",
    desc: "Thai-style cola. Spiced, less sweet.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "bottle", base: "#3a1d0a", label: "COLA\nBURI", labelBg: "#fee2c8", inkOnLabel: "#5a1d04" } },
  { id: "classic-craft-soda", cat: "soda", name: "Classic Signature Soda", thai: "คลาสสิค คราฟต์โซดา",
    desc: "House recipe — blackberry, anise, spices.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "bottle", base: "#5a2840", label: "CLASSIC", labelBg: "#fde6f0", inkOnLabel: "#3a0a20" } },
  { id: "peach-zero", cat: "soda", name: "Peach No Sugar", thai: "พีช ซีโร่",
    desc: "Peach soda. Zero sugar.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "bottle", base: "#e89b7c", label: "PEACH\nZERO", labelBg: "#fef3e9", inkOnLabel: "#7a3018" } },
  { id: "passion-pineapple", cat: "soda", name: "Passion Fruit Pineapple", thai: "พาสชั่นฟรุ๊ต-ไพน์แอปเปิ้ล",
    desc: "Passion fruit + pineapple. Tropical fizz.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "bottle", base: "#e8b340", label: "PASSION\nFRUIT", labelBg: "#fff4d0", inkOnLabel: "#5a3a08" } },
  { id: "ginger-lemon-soda", cat: "soda", name: "Ginger Lemon Soda", thai: "ขิงเลมอน โซดา",
    desc: "Ginger root + lemon. Punchy, warming.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "can", base: "#f4dc4a", label: "GINGER\nLEMON", labelBg: "#fffbe6", inkOnLabel: "#3a2c0a" } },
  { id: "peach-lychee-soda", cat: "soda", name: "Peach Lychee Soda", thai: "พีชลิ้นจี่ โซดา",
    desc: "Peach + lychee. Soft, floral.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "can", base: "#ecc2c8", label: "PEACH\nLYCHEE", labelBg: "#fde8eb", inkOnLabel: "#5a1830" } },
  { id: "muscat-grapes-zero", cat: "soda", name: "Muscat Grapes Zero", thai: "องุ่นไซมัสคัส ซีโร่",
    desc: "Muscat grape soda. Zero sugar.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "bottle", base: "#a8c860", label: "MUSCAT\nGRAPES", labelBg: "#f0fac8", inkOnLabel: "#2a4a08" } },
  { id: "pineapple-paradise", cat: "soda", name: "Pineapple Paradise", thai: "ไพน์แอปเปิล พาราไดซ์",
    desc: "Pineapple, ginger, lime.",
    price: 89, temps: ["iced"], opts: [],
    recipe: { type: "bottle", base: "#f0c440", label: "PINEAPPLE\nPARADISE", labelBg: "#fff4d0", inkOnLabel: "#5a3a08" } },

  // ───────── JUICE & MORE ─────────
  { id: "orange-juice", cat: "juice", name: "Orange Juice", thai: "น้ำส้ม",
    desc: "Fresh 100% orange. No sugar added.",
    price: 65, temps: ["iced"], opts: [],
    recipe: { type: "iced", base: "#f08d2a", top: null, label: "ORANGE" } },
  { id: "coconut-water", cat: "juice", name: "Coconut Water", thai: "น้ำมะพร้าว",
    desc: "Fresh 100% coconut water. No sugar added.",
    price: 65, temps: ["iced"], opts: [],
    recipe: { type: "iced", base: "#f4ede2", top: null, label: "COCONUT" } },
  { id: "longan-drink", cat: "juice", name: "Longan Drink", thai: "น้ำลำไย",
    desc: "Sweet longan-fruit drink. Thai classic.",
    price: 69, temps: ["iced"], opts: [],
    recipe: { type: "can", base: "#c83828", label: "LONGAN\nDRINK", labelBg: "#fef0e8", inkOnLabel: "#7a1a08" } },
  { id: "chrysanthemum-tea", cat: "juice", name: "Chrysanthemum Tea", thai: "เก๊กฮวย",
    desc: "Cooling chrysanthemum-flower tea.",
    price: 69, temps: ["iced"], opts: [],
    recipe: { type: "can", base: "#f4cc28", label: "CHRYSAN-\nTHEMUM", labelBg: "#fffbe2", inkOnLabel: "#6a4810" } },
  { id: "winter-melon", cat: "juice", name: "Winter Melon Drink", thai: "น้ำฟักเขียว",
    desc: "Sweet winter-melon herbal drink.",
    price: 69, temps: ["iced"], opts: [],
    recipe: { type: "can", base: "#2c7a3e", label: "WINTER\nMELON", labelBg: "#e6f4ea", inkOnLabel: "#1a4a24" } },
  { id: "chinese-herbal-tea", cat: "juice", name: "Chinese Herbal Tea", thai: "จับเลี้ยง",
    desc: "Cooling herbal-tea blend.",
    price: 69, temps: ["iced"], opts: [],
    recipe: { type: "can", base: "#a8202a", label: "HERBAL\nTEA", labelBg: "#fdeaec", inkOnLabel: "#5a1018" } },

  // ───────── SUMMER SPECIALS ─────────
  { id: "americano-cloudy-yogurt", cat: "summer", name: "Americano Cloudy Yogurt", thai: "อเมริกาโน่ คลาวด์ดี้ โยเกิร์ต",
    desc: "Honduras coffee + cloudy yogurt finish.",
    price: 165, temps: ["iced"], opts: ["sugar", "roast"],
    recipe: { type: "iced", base: "#2a1810", top: "#f5ede0", topPct: 0.40, label: "CLOUDY\nYOGURT" } },

  // ───────── HOT MENU ─────────
  { id: "hot-americano", cat: "hot", name: "Hot Americano", thai: "อเมริกาโน่ร้อน",
    desc: "Bright espresso, hot water. Pure.",
    price: 75, temps: ["hot"], opts: ["sugar", "roast"],
    recipe: { type: "hot", base: "#2a1810", top: null, label: "AMERICANO" } },
  { id: "hot-latte", cat: "hot", name: "Hot Latte", thai: "ลาเต้ร้อน",
    desc: "Steamed milk + espresso + heart latte art.",
    price: 89, temps: ["hot"], opts: ["sugar", "roast"],
    recipe: { type: "hot", base: "#7e5234", top: "#f1e2c9", topPct: 0.62, art: "heart", label: "LATTE" } },
  { id: "hot-cocoa", cat: "hot", name: "Hot Cocoa", thai: "โกโก้ร้อน",
    desc: "Hot real cocoa + milk + cocoa dusting.",
    price: 75, temps: ["hot"], opts: ["sugar"],
    recipe: { type: "hot", base: "#5a3220", top: "#e8d4b8", topPct: 0.62, art: "leaf", label: "COCOA" } },
  { id: "hot-mocha", cat: "hot", name: "Hot Mocha", thai: "มอคค่าร้อน",
    desc: "Espresso + chocolate + steamed milk.",
    price: 89, temps: ["hot"], opts: ["sugar", "roast"],
    recipe: { type: "hot", base: "#3a2418", top: "#d8c0a4", topPct: 0.58, art: "leaf", label: "MOCHA" } },
  { id: "hot-caramel-macchiato", cat: "hot", name: "Hot Caramel Macchiato", thai: "คาราเมลแมคคิอาโต้ร้อน",
    desc: "Caramel + vanilla + layered espresso.",
    price: 89, temps: ["hot"], opts: ["sugar", "roast"],
    recipe: { type: "hot", base: "#7c5232", top: "#e8d4b4", topPct: 0.60, art: "lattice", label: "MACCHIATO" } },
  { id: "hot-thai-tea", cat: "hot", name: "Hot Thai Tea", thai: "ชาไทยร้อน",
    desc: "Hot Thai tea + condensed milk.",
    price: 79, temps: ["hot"], opts: ["sugar"],
    recipe: { type: "hot", base: "#d56831", top: "#e8d4b8", topPct: 0.58, art: "heart", label: "THAI TEA" } },
  { id: "hot-matcha-latte", cat: "hot", name: "Hot Matcha Latte", thai: "มัทฉะลาเต้ร้อน",
    desc: "Japanese matcha + hot milk + heart art.",
    price: 79, temps: ["hot"], opts: ["sugar"],
    recipe: { type: "hot", base: "#5a8038", top: "#eee4d2", topPct: 0.58, art: "heart", label: "MATCHA" } },

  // ───────── OTHER (custom drink — staff types the name) ─────────
  { id: "other-drink", cat: "other", name: "Other drink", thai: "อื่นๆ",
    desc: "Not on the menu? Type the drink you want and we'll ask the cafe.",
    temps: ["iced", "hot"], opts: ["sugar"], custom: true,
    recipe: { type: "iced", base: "#c8c0a8", top: null, label: "OTHER" } }
];

window.MENU_CATEGORIES.push({ id: "other", label: "Other" });

// Option vocabularies — used by the customize sheet.
// Labels are i18n keys so the chips can render in TH or EN.
window.MENU_OPTIONS = {
  sugar: [
    { id: "0",   label: "No sugar", i18n: "opt.sugar.0" },
    { id: "25",  label: "25%" },
    { id: "50",  label: "50%" },
    { id: "75",  label: "75%" },
    { id: "100", label: "100%" },
    { id: "125", label: "125%" },
    { id: "150", label: "150%" },
    { id: "175", label: "175%" },
    { id: "200", label: "200%" }
  ],
  // Roast appears only on coffee drinks (espresso cat, hot coffees, americano-cloudy-yogurt).
  roast: [
    { id: "light",  label: "Light",  i18n: "opt.roast.light" },
    { id: "medium", label: "Medium", i18n: "opt.roast.medium" },
    { id: "dark",   label: "Dark",   i18n: "opt.roast.dark" }
  ]
};
